name: Create release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_call:
    inputs:
      upstream_version:
        description: The upstream version
        required: false
        type: string
  workflow_dispatch:

permissions:
  contents: write

env:
  GIT_USER_NAME: Fra Bot
  GIT_USER_EMAIL: fragoibot@gmail.com
  DEBPACKAGE: hello-world
  DEBDIST: focal
  PPA: ppa:fragoi/test

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fragoi/bash-actions@main

      - name: Create version
        run: |
          debNewVersion "${{ inputs.upstream_version }}"

      - name: Download upstream source
        run: |
          downloadTag fragoi/hello-world v$(debChangelogUpver)
          ls -l

      - if: false
        name: Build source package
        uses: fragoi/debuild-action@main
        with:
          ppa: ${{ env.PPA }}
